#!/bin/bash

tmux -S ~/tst new-window -n "tst-$1-$2-$3"
tmux -S ~/tst send-keys "z3ta" C-m
tmux -S ~/tst send-keys "prooftrace_$1_tst_run configs/prooftrace_$1.json --sync_dir=~/tmp/iota/$1-$2 --device=cuda:$3" C-m
