#!/bin/bash

tmux -S ~/lm_ack new-window -n "lm-ack-$1-$2"
tmux -S ~/lm_ack send-keys "z3ta" C-m
tmux -S ~/lm_ack send-keys "prooftrace_lm_ack_run configs/prooftrace_lm.json --sync_dir=~/tmp/iota/lm-$1 --rollout_dir=~/tmp/iota/lm-1-rollouts --device=cuda:$2" C-m
