#!/bin/bash

tmux -S ~/lm_tst new-window -n "lm-tst-$1-$2"
tmux -S ~/lm_tst send-keys "z3ta" C-m
tmux -S ~/lm_tst send-keys "prooftrace_lm_tst_run configs/prooftrace_lm.json --sync_dir=~/tmp/iota/lm-$1 --rollout_dir=~/tmp/iota/lm-$1-rollouts --device=cuda:$2" C-m
