#!/bin/bash

tmux -S ~/ppo_ack new-window -n "ppo-ack-$1-$2"
tmux -S ~/ppo_ack send-keys "z3ta" C-m
tmux -S ~/ppo_ack send-keys "prooftrace_ppo_ack_run configs/prooftrace_ppo.json --sync_dir=~/tmp/iota/ppo-$1 --device=cuda:$2" C-m
