#!/bin/bash

tmux -S ~/rll new-window -n "rollout_wrk-$1-$2"
tmux -S ~/rll send-keys "z3ta" C-m
tmux -S ~/rll send-keys "prooftrace_search_rollout_wrk_run configs/prooftrace_search.json --sync_dir=~/tmp/iota/search-$1 --rollout_dir=~/tmp/iota/search-$1-rollouts --device=cuda:$2" C-m
