#!/bin/bash

tmux -S ~/v_tst new-window -n "v-tst-$1-$2"
tmux -S ~/v_tst send-keys "z3ta" C-m
tmux -S ~/v_tst send-keys "prooftrace_v_tst_run configs/prooftrace_v.json --sync_dir=~/tmp/iota/v-$1 --rollout_dir=~/tmp/iota/lm-$1-rollouts --device=cuda:$2" C-m
